{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mikepenz",
    "module": "multiplatform-markdown-renderer-code",
    "version": "0.45.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.7.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "com.mikepenz",
          "module": "multiplatform-markdown-renderer",
          "version": {
            "requires": "0.45.0"
          }
        },
        {
          "group": "dev.snipme",
          "module": "highlights",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "multiplatform-markdown-renderer-code-metadata-0.45.0.jar",
          "url": "multiplatform-markdown-renderer-code-0.45.0.jar",
          "size": 3015,
          "sha512": "9db22f616f14e4f65a3588a9a38be32fa6c6861dec561b108f3492f9592a07d929ac1915d2534bbfc9b0ace71a09dee7346be855b13db4ddf9f5b98eed6b4919",
          "sha256": "559706223c77966c43caeff344320fb7c1d5d3ab8e3f56eedfc1825e6dd8f1bf",
          "sha1": "3bc55c26d41efa288a05dc3cac58d8396de7b9b9",
          "md5": "b693d68f74ca73e6b443d8afc205d410"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "multiplatform-markdown-renderer-code-kotlin-0.45.0-sources.jar",
          "url": "multiplatform-markdown-renderer-code-0.45.0-sources.jar",
          "size": 2755,
          "sha512": "0c7f88c0453228ecbd94a2d79424b4f08b178e2229dc95bce8576ab0be4b7a712f266d49ec5325221f55e85464bb4a14d857055e0e5c476e9067249ccb29b57b",
          "sha256": "d566ef368bb3b7b6d60399f452d2c8da5751a4e22d462899fe102fb8e1de2f9a",
          "sha1": "78bd7f943f98f3445204140eaaa297f46fa0ac14",
          "md5": "ebcdc24661a750f9600722f584e28cea"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "https://repo1.maven.org/maven2/com/mikepenz/multiplatform-markdown-renderer-code-android/0.45.0/multiplatform-markdown-renderer-code-android-0.45.0.module",
        "group": "com.mikepenz",
        "module": "multiplatform-markdown-renderer-code-android",
        "version": "0.45.0"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "https://repo1.maven.org/maven2/com/mikepenz/multiplatform-markdown-renderer-code-android/0.45.0/multiplatform-markdown-renderer-code-android-0.45.0.module",
        "group": "com.mikepenz",
        "module": "multiplatform-markdown-renderer-code-android",
        "version": "0.45.0"
      }
    },
    {
      "name": "androidSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "https://repo1.maven.org/maven2/com/mikepenz/multiplatform-markdown-renderer-code-android/0.45.0/multiplatform-markdown-renderer-code-android-0.45.0.module",
        "group": "com.mikepenz",
        "module": "multiplatform-markdown-renderer-code-android",
        "version": "0.45.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "https://repo1.maven.org/maven2/com/mikepenz/multiplatform-markdown-renderer-code-iosarm64/0.45.0/multiplatform-markdown-renderer-code-iosarm64-0.45.0.module",
        "group": "com.mikepenz",
        "module": "multiplatform-markdown-renderer-code-iosarm64",
        "version": "0.45.0"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "https://repo1.maven.org/maven2/com/mikepenz/multiplatform-markdown-renderer-code-iosarm64/0.45.0/multiplatform-markdown-renderer-code-iosarm64-0.45.0.module",
        "group": "com.mikepenz",
        "module": "multiplatform-markdown-renderer-code-iosarm64",
        "version": "0.45.0"
      }
    },
    {
      "name": "iosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "https://repo1.maven.org/maven2/com/mikepenz/multiplatform-markdown-renderer-code-iosarm64/0.45.0/multiplatform-markdown-renderer-code-iosarm64-0.45.0.module",
        "group": "com.mikepenz",
        "module": "multiplatform-markdown-renderer-code-iosarm64",
        "version": "0.45.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "https://repo1.maven.org/maven2/com/mikepenz/multiplatform-markdown-renderer-code-iosarm64/0.45.0/multiplatform-markdown-renderer-code-iosarm64-0.45.0.module",
        "group": "com.mikepenz",
        "module": "multiplatform-markdown-renderer-code-iosarm64",
        "version": "0.45.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "https://repo1.maven.org/maven2/com/mikepenz/multiplatform-markdown-renderer-code-iossimulatorarm64/0.45.0/multiplatform-markdown-renderer-code-iossimulatorarm64-0.45.0.module",
        "group": "com.mikepenz",
        "module": "multiplatform-markdown-renderer-code-iossimulatorarm64",
        "version": "0.45.0"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "https://repo1.maven.org/maven2/com/mikepenz/multiplatform-markdown-renderer-code-iossimulatorarm64/0.45.0/multiplatform-markdown-renderer-code-iossimulatorarm64-0.45.0.module",
        "group": "com.mikepenz",
        "module": "multiplatform-markdown-renderer-code-iossimulatorarm64",
        "version": "0.45.0"
      }
    },
    {
      "name": "iosSimulatorArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "https://repo1.maven.org/maven2/com/mikepenz/multiplatform-markdown-renderer-code-iossimulatorarm64/0.45.0/multiplatform-markdown-renderer-code-iossimulatorarm64-0.45.0.module",
        "group": "com.mikepenz",
        "module": "multiplatform-markdown-renderer-code-iossimulatorarm64",
        "version": "0.45.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "https://repo1.maven.org/maven2/com/mikepenz/multiplatform-markdown-renderer-code-iossimulatorarm64/0.45.0/multiplatform-markdown-renderer-code-iossimulatorarm64-0.45.0.module",
        "group": "com.mikepenz",
        "module": "multiplatform-markdown-renderer-code-iossimulatorarm64",
        "version": "0.45.0"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "https://repo1.maven.org/maven2/com/mikepenz/multiplatform-markdown-renderer-code-js/0.45.0/multiplatform-markdown-renderer-code-js-0.45.0.module",
        "group": "com.mikepenz",
        "module": "multiplatform-markdown-renderer-code-js",
        "version": "0.45.0"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "https://repo1.maven.org/maven2/com/mikepenz/multiplatform-markdown-renderer-code-js/0.45.0/multiplatform-markdown-renderer-code-js-0.45.0.module",
        "group": "com.mikepenz",
        "module": "multiplatform-markdown-renderer-code-js",
        "version": "0.45.0"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "https://repo1.maven.org/maven2/com/mikepenz/multiplatform-markdown-renderer-code-js/0.45.0/multiplatform-markdown-renderer-code-js-0.45.0.module",
        "group": "com.mikepenz",
        "module": "multiplatform-markdown-renderer-code-js",
        "version": "0.45.0"
      }
    },
    {
      "name": "jsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "https://repo1.maven.org/maven2/com/mikepenz/multiplatform-markdown-renderer-code-js/0.45.0/multiplatform-markdown-renderer-code-js-0.45.0.module",
        "group": "com.mikepenz",
        "module": "multiplatform-markdown-renderer-code-js",
        "version": "0.45.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "https://repo1.maven.org/maven2/com/mikepenz/multiplatform-markdown-renderer-code-jvm/0.45.0/multiplatform-markdown-renderer-code-jvm-0.45.0.module",
        "group": "com.mikepenz",
        "module": "multiplatform-markdown-renderer-code-jvm",
        "version": "0.45.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "https://repo1.maven.org/maven2/com/mikepenz/multiplatform-markdown-renderer-code-jvm/0.45.0/multiplatform-markdown-renderer-code-jvm-0.45.0.module",
        "group": "com.mikepenz",
        "module": "multiplatform-markdown-renderer-code-jvm",
        "version": "0.45.0"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "https://repo1.maven.org/maven2/com/mikepenz/multiplatform-markdown-renderer-code-jvm/0.45.0/multiplatform-markdown-renderer-code-jvm-0.45.0.module",
        "group": "com.mikepenz",
        "module": "multiplatform-markdown-renderer-code-jvm",
        "version": "0.45.0"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "https://repo1.maven.org/maven2/com/mikepenz/multiplatform-markdown-renderer-code-macosarm64/0.45.0/multiplatform-markdown-renderer-code-macosarm64-0.45.0.module",
        "group": "com.mikepenz",
        "module": "multiplatform-markdown-renderer-code-macosarm64",
        "version": "0.45.0"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "https://repo1.maven.org/maven2/com/mikepenz/multiplatform-markdown-renderer-code-macosarm64/0.45.0/multiplatform-markdown-renderer-code-macosarm64-0.45.0.module",
        "group": "com.mikepenz",
        "module": "multiplatform-markdown-renderer-code-macosarm64",
        "version": "0.45.0"
      }
    },
    {
      "name": "macosArm64ResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresources",
        "org.gradle.usage": "kotlin-multiplatformresources",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "https://repo1.maven.org/maven2/com/mikepenz/multiplatform-markdown-renderer-code-macosarm64/0.45.0/multiplatform-markdown-renderer-code-macosarm64-0.45.0.module",
        "group": "com.mikepenz",
        "module": "multiplatform-markdown-renderer-code-macosarm64",
        "version": "0.45.0"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "https://repo1.maven.org/maven2/com/mikepenz/multiplatform-markdown-renderer-code-macosarm64/0.45.0/multiplatform-markdown-renderer-code-macosarm64-0.45.0.module",
        "group": "com.mikepenz",
        "module": "multiplatform-markdown-renderer-code-macosarm64",
        "version": "0.45.0"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "https://repo1.maven.org/maven2/com/mikepenz/multiplatform-markdown-renderer-code-wasm-js/0.45.0/multiplatform-markdown-renderer-code-wasm-js-0.45.0.module",
        "group": "com.mikepenz",
        "module": "multiplatform-markdown-renderer-code-wasm-js",
        "version": "0.45.0"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "https://repo1.maven.org/maven2/com/mikepenz/multiplatform-markdown-renderer-code-wasm-js/0.45.0/multiplatform-markdown-renderer-code-wasm-js-0.45.0.module",
        "group": "com.mikepenz",
        "module": "multiplatform-markdown-renderer-code-wasm-js",
        "version": "0.45.0"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "https://repo1.maven.org/maven2/com/mikepenz/multiplatform-markdown-renderer-code-wasm-js/0.45.0/multiplatform-markdown-renderer-code-wasm-js-0.45.0.module",
        "group": "com.mikepenz",
        "module": "multiplatform-markdown-renderer-code-wasm-js",
        "version": "0.45.0"
      }
    },
    {
      "name": "wasmJsResourcesElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.libraryelements": "kotlin-multiplatformresourcesjs",
        "org.gradle.usage": "kotlin-multiplatformresourcesjs",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "https://repo1.maven.org/maven2/com/mikepenz/multiplatform-markdown-renderer-code-wasm-js/0.45.0/multiplatform-markdown-renderer-code-wasm-js-0.45.0.module",
        "group": "com.mikepenz",
        "module": "multiplatform-markdown-renderer-code-wasm-js",
        "version": "0.45.0"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "com.mikepenz",
          "module": "multiplatform-markdown-renderer",
          "version": {
            "requires": "0.45.0"
          }
        },
        {
          "group": "dev.snipme",
          "module": "highlights",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "multiplatform-markdown-renderer-code-linuxX64Main-0.45.0.klib",
          "url": "multiplatform-markdown-renderer-code-linuxX64Main-0.45.0.klib"
        }
      ]
    }
  ]
}